### ISSUE TITLE
The code does not follow Python Styling Guide

### ISSUE THREAD

**Issue by PritamDutt** [zaimusho/AWS-Polling-Assignment#1]
Please have a look @ https://www.python.org/dev/peps/pep-0008/ to understand Python Styling Guide

You should also read on Python code [linters](http://pylint.pycqa.org/en/latest/) and [formatters](https://black.readthedocs.io/en/stable/).

You should also introduce yourself to following tools:
- [bandit](https://bandit.readthedocs.io/en/latest/)
- [isort](https://github.com/PyCQA/isort)
- [flake8](https://gitlab.com/pycqa/flake8)
- [pytest](https://github.com/pytest-dev/pytest)

In addition to this couple of important tools/ technologies you need to make yourself aware of:
- [Django](https://www.djangoproject.com/) - Product Web Framework
- [PostgreSQL](https://www.postgresql.org/) - Product Database

**Comment by zaimusho** [comment]
> Please have a look @ https://www.python.org/dev/peps/pep-0008/ to understand Python Styling Guide
> 
> You should also read on Python code [linters](http://pylint.pycqa.org/en/latest/) and [formatters](https://black.readthedocs.io/en/stable/).
> 
> You should also introduce yourself to following tools:
> 
> * [bandit](https://bandit.readthedocs.io/en/latest/)
> * [isort](https://github.com/PyCQA/isort)
> * [flake8](https://gitlab.com/pycqa/flake8)
> * [pytest](https://github.com/pytest-dev/pytest)
> 
> In addition to this couple of important tools/ technologies you need to make yourself aware of:
> 
> * [Django](https://www.djangoproject.com/) - Product Web Framework
> * [PostgreSQL](https://www.postgresql.org/) - Product Database
